### ISSUE TITLE
[Bug] Doesn't work after installation

### ISSUE THREAD

**Issue by kaiserkueche** [spotify-util/ViewPlaylistsWithSong#9]
Hello,

I tried installing the extension how you said, and did `spicetify apply`, tried reinstalling several time but the button doesn't show up and it is as if I didn't install it.

I also have `BetterLeftSidebar, copyPlaylistInfo, genre, hidePodcasts` installed and here is my `config-xpui.ini`:

```
[Setting]
spotify_path            = /opt/spotify
prefs_path              = /home/kaiser/.config/spotify/prefs
replace_colors          = 1
overwrite_assets        = 0
spotify_launch_flags    = 
check_spicetify_upgrade = 0
current_theme           = Sleek
color_scheme            = 
inject_css              = 1

[Preprocesses]
expose_apis           = 1
disable_upgrade_check = 1
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1

[AdditionalOptions]
home_config           = 1
experimental_features = 1
extensions            = hidePodcasts.js|BetterLeftSidebar.js|genre.js|ViewPlaylistsWithSong.js|bookmark.js|keyboardShortcut.js|popupLyrics.js|shuffle+.js|copyPlaylistInfo.js
custom_apps           = 
sidebar_config        = 1

[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.1.84.716.gc5f8b819
with    = 2.11.1
```

If you need more information to help me, please let me know. I hope we find a solution because your extension is exactely what I need since ages to help sorting my songs and it will be very helpful!

**Comment by elijaholmos** [comment]
Hi @kaizokuroo! Sorry this wasn't working for you. From the config file you shared, it looks like your Spotify version is `1.1.84 `and your Spicetify version is `2.11.1`. Unfortunately, this extension only works with legacy Spotify (`<=1.1.58`) and Spicetify (`<=1.2.1`). I haven't yet ported it over to the latest version of Spotify/Spicetify because I dislike the new UI and am still using legacy myself 😅 

It's possible that I (or someone else) will port this over in the future, but there aren't any current plans. You can "watch" the repo using the eye icon on the top right of the webpage to get notified of any new releases. Sorry about the inconvenience.
